### ISSUE TITLE
Hello fellow reverse engineer

### ISSUE THREAD

**Issue by skraus-dev** [luv4bytes/cherrymxboard30s-rgb#1]
Cool to see somebody else taking the plunge.

Maybe this can help a bit with unknown structures of packets.

https://github.com/skraus-dev/cherryrgb-rs

Also, the protocol seems to be quite related to EVision/Sonix: https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/2057

I saw you posted there already: https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/1472

cheers

**Comment by luv4bytes** [comment]
@skraus-dev Thanks so much for the link to your repo! Definitely going to check it out the next days! 😄
